
export const GET_ALL_ARTICLES="GET_ALL_ARTICLES";
export const GET_ALL_USERS="GET_ALL_USERS"
export const GET_NUMBER_USERS="GET_NUMBER_USERS"
export const GET_HISTORIQUE="GET_HISTORIQUE"
export const GET_USEREXIST="GET_USEREXIST"
